apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance-controller
spec:
  selector:
    matchLabels:
      run: instance-controller
  template:
    metadata:
      labels:
        run: instance-controller
        app.kubernetes.io/component: web-tier
    spec:
      serviceAccountName: instance-controller
      volumes:
      - name: charts-volume
        hostPath:
          path: /charts
          type: Directory
      containers:
      - name: instance-controller
        {{- if (not .Values.instance_controller_image) }}
        {{- fail ".Values.instance_controller_image must be specified"}}
        {{- end }}
        image: {{ .Values.instance_controller_image }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: charts-volume
          mountPath: /charts
