apiVersion: v1
kind: ServiceAccount
metadata:
  name: instance-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: namespace-creator
  labels:
    instance-controller-role: "true"
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: namespace-populator
  labels:
    instance-controller-role: "true"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instance-controller-aggregator
aggregationRule:
  clusterRoleSelectors: 
  - matchLabels:
      instance-controller-role: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instance-controller
subjects:
- kind: ServiceAccount
  name: instance-controller
  namespace: default
roleRef: 
  kind: ClusterRole
  name: instance-controller-aggregator
