apiVersion: v1
kind: Service
metadata:
  name: web-tier
spec:
  type: NodePort
  ports:  
  - port: 8080
    targetPort: 8080
    nodePort: 31393
    protocol: TCP
  selector:
    app.kubernetes.io/component: web-tier